### ISSUE TITLE
Running frontend in local system

### ISSUE THREAD

**Issue by SanidhyaD** [Princegupta101/Live-Code-Share#1]
When trying to run frontend, I am facing errors like "Could not resolve "core-js-pure/stable/object/assign.js"

    node_modules/react-avatar/es/avatar.js:4:27:
      4 │ import _Object$assign from "core-js-pure/stable/object/assign.js";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js-pure/stable/object/assign.js" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle."

**Comment by Princegupta101** [comment]
I've checked on my side, and everything is working fine. I also tried it on another laptop using a fresh clone, and everything is working there as well.

I think the problem might be on your side, possibly with your environment setup or an npm issue. 
@SanidhyaD
